<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Trumpf.Coparoo.Waiting\Trumpf.Coparoo.Waiting.csproj" />
    <ProjectReference Include="..\Trumpf.Coparoo.Waiting.WinForms\Trumpf.Coparoo.Waiting.WinForms.csproj" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.3" />
    <PackageReference Include="AwesomeAssertions" Version="9.3.0" />
  </ItemGroup>
</Project>